### ISSUE TITLE
access method "pg_tde" dos not exist

### ISSUE THREAD

**Issue by DaveStokesPercona** [Percona-Lab/postgres-tde-ext#43]
Loaded Docker image, attempted to create a table with 'USING pg_tde' and received ERROR" access method "pg_tde" does not exist.

create table sbtest (id serial, k integer default '0' not null, primary key (id)) using pg_tde; <- copied from something in the postgres-tde-ext.conf file in the psotgres-tde-ext on Githuib

**Comment by dutow** [comment]
@DaveStokesPercona Try executing `CREATE EXTENSION pg_tde;`, most  likely the Dockerfile doesn't enable the extension to the default database by default.
`

**Comment by capri1989** [comment]
As you can see from the documentation, it prepares the whole setup, but you still need to create the extension.

https://github.com/Percona-Lab/postgres-tde-ext#run-in-docker

**Comment by dAdAbird** [comment]
Hi @DaveStokesPercona 
The image should be creating the extension. This is from docker run logs:
```
...
2023-10-11 07:06:04.400 GMT [52] LOG:  database system was shut down at 2023-10-11 07:06:04 GMT
2023-10-11 07:06:04.404 GMT [49] LOG:  database system is ready to accept connections
 done
server started

/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/pg-tde-create-ext.sql
CREATE EXTENSION

...
```

Are you using the default database?

**Comment by DaveStokesPercona** [comment]
Here are the steps I am taking. I rebooted my test laptop, restarted the Docker image, and got better results.

sudo docker run --name pg-tde -e POSTGRES_PASSWORD=mysecretpassword -d perconalab/postgres-tde-ext
2ccbe758f32348e286cb277aed17c1c3f9c880b37f92303bd2266a334096b0b1
stoker@testa:~$ !136
sudo docker run -it --rm postgres psql -h 172.17.0.2 -U postgres
Password for user postgres: 
psql (16.0 (Debian 16.0-1.pgdg120+1))
Type "help" for help.

postgres=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description          
---------+---------+------------+------------------------------
 pg_tde  | 1.0     | public     | pg_tde access method
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

postgres=# CREATE EXTENSION pg_tde;
ERROR:  extension "pg_tde" already exists
postgres=# 

postgres=# CREATE TABLE sbtest1 ( id SERIAL, k INTEGER DEFAULT '0' NOT NULL, PRIMARY KEY (id)) USING pg_tde;
CREATE TABLE
postgres=# \d sbtest1;
                            Table "public.sbtest1"
 Column |  Type   | Collation | Nullable |               Default               
--------+---------+-----------+----------+-------------------------------------
 id     | integer |           | not null | nextval('sbtest1_id_seq'::regclass)
 k      | integer |           | not null | 0
Indexes:
    "sbtest1_pkey" PRIMARY KEY, btree (id)

postgres=# 
 

postgres=# SELECT cmin, cmax, xmin, xmax, ctid, * FROM sbtest1;
 cmin | cmax | xmin | xmax |  ctid  | id | k  
------+------+------+------+--------+----+----
    0 |    0 |  744 |    0 | (0,1)  |  1 |  1
    0 |    0 |  744 |    0 | (0,2)  |  2 |  2
    0 |    0 |  744 |    0 | (0,3)  |  3 |  3
    0 |    0 |  744 |    0 | (0,7)  |  7 |  7
    0 |    0 |  744 |    0 | (0,8)  |  8 |  8
    0 |    0 |  744 |    0 | (0,9)  |  9 |  9
    0 |    0 |  744 |    0 | (0,10) | 10 | 10
    0 |    0 |  746 |    0 | (0,11) | 11 | 11
    0 |    0 |  746 |    0 | (0,12) | 12 | 12
    0 |    0 |  746 |    0 | (0,13) | 13 | 13
(10 rows)

postgres=# 

1. I am not sure what changed to get the 'CREATE .... USING pg_tde;' to work. It may be something in a reboot/restart.
2. I will keep testing and will probably start a blog.  And this might be a good presentation for a show like SCaLE.
3

**Comment by dAdAbird** [comment]
Maybe it was a connection to some other postgres instance or you used non-default databases...
Anyway, I'm closing this issue but feel free to reopen it or create a new one if needed

**Comment by DaveStokesPercona** [comment]
When you create a new database, \c to it, and try to create a table, the access method 'pg_tde' does not exist  reappears. In the following I create to new databases

ostgres=# create database kai;
CREATE DATABASE
postgres=# \c kai;
You are now connected to database "kai" as user "postgres".
kai=# CREATE TABLE sbtest1 ( id SERIAL, k INTEGER DEFAULT '0' NOT NULL, PRIMARY KEY (id)) USING pg_tde;
ERROR:  access method "pg_tde" does not exist
kai=# create extension pg_tde;
CREATE EXTENSION
kai=# CREATE TABLE sbtest1 ( id SERIAL, k INTEGER DEFAULT '0' NOT NULL, PRIMARY KEY (id)) USING pg_tde;
CREATE TABLE
kai=# insert into sbtest1 (k) select generate_series(1,100);
INSERT 0 100
kai=# 


kai=# create database davetest;
CREATE DATABASE
kai=# \c davetest
You are now connected to database "davetest" as user "postgres".
davetest=# CREATE TABLE sbtest1 ( id SERIAL, k INTEGER DEFAULT '0' NOT NULL, PRIMARY KEY (id)) USING pg_tde;
ERROR:  access method "pg_tde" does not exist
davetest=#

**Comment by capri1989** [comment]
Can you rerun your testing? Since https://github.com/Percona-Lab/postgres-tde-ext/pull/45 was merged, pg_tde is added by default and will be created for all databases.

**Comment by jeffreydwalter** [comment]
@ImTheKai I know this is old, but I'm new to this project and just ran the `latest` docker image and am seeing this exact behavior. This doesn't seem fixed.

**Comment by jeffreydwalter** [comment]
Dig some digging and it looks like the access method is registered as `pg_tde_basic` not `pg_tde`.
```
pg_tde_test=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description          
---------+---------+------------+------------------------------
 pg_tde  | 1.0     | public     | pg_tde access method
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

pg_tde_test=# CREATE TABLE tde_test (id integer) USING pg_tde;
ERROR:  access method "pg_tde" does not exist
pg_tde_test=# SELECT * FROM pg_am;
  oid  |    amname    |       amhandler        | amtype 
-------+--------------+------------------------+--------
     2 | heap         | heap_tableam_handler   | t
   403 | btree        | bthandler              | i
   405 | hash         | hashhandler            | i
   783 | gist         | gisthandler            | i
  2742 | gin          | ginhandler             | i
  4000 | spgist       | spghandler             | i
  3580 | brin         | brinhandler            | i
 16412 | pg_tde_basic | pg_tdeam_basic_handler | t
(8 rows)

pg_tde_test=# CREATE TABLE tde_test (id integer) USING pg_tde_basic;
ERROR:  failed to retrieve principal key
pg_tde_test=# CREATE TABLE tde_test (id integer) USING pg_tde;
ERROR:  access method "pg_tde" does not exist
pg_tde_test=# CREATE EXTENSION pg_tde;
ERROR:  extension "pg_tde" already exists
```

**Comment by jeffreydwalter** [comment]
Opened https://github.com/Percona-Lab/pg_tde/issues/244
