### ISSUE TITLE
It is not clear that the user has to explicitly set the access method

### ISSUE THREAD

**Issue by waltton** [Percona-Lab/postgres-tde-ext#87]
I followed the instructions well enough to have the database up to run some tests, after realizing I had no performance drop I started reviewing the docs, when I got to the end of ["Test Transparent Data Encryption"](https://percona-lab.github.io/postgres-tde-ext/main/test.html) I got stuck for a while, from the docs it seems that I did everything right.

Maybe I missed it in some other place but I saw no mention that I had to set the access method for my test table explicitly, I assumed that the extension itself would set `default_table_access_method` and did not check. 

I believe that other users not so familiar with access methods would struggle.

**Comment by capri1989** [comment]
Hey,

thanks a lot for your report. We've been working on a new updated version of the documentation, which is not yet the default.

Can you check it out and let us know if this makes it clearer?

https://percona-lab.github.io/postgres-tde-ext/main/setup.html

**Comment by waltton** [comment]
Hi @capri1989 

I found the new docs earlier, but I think that there is still something missing.

Point 3 gave me the impression that just by enabling the extension I would have the encryption enabled but that is not the case.

I think that in between current point 3 and 4 could be another point or hit saying something like:

> `CREATE EXTENSION pg_tde` will enable the `pg_tde` access method.
To enable encryption by default you need to set `default_table_access_method` to `pg_tde`
Or specify the access method when creating a new table `CREATE TABLE example (value TEXT) USING pg_tde`

**Comment by capri1989** [comment]
Hi @waltton,

could you please take a look at the documentation PR that was created by @nastena1606? Does that make it clearer and looks alright?

Thanks,
Kai
